import { jsPDF } from 'jspdf';

export const generateSafetyChecklistPDF = () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Reloading Safety Checklist', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Print and keep this checklist at your reloading bench', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 15;
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Critical Safety Rules
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Critical Safety Rules - Review Before EVERY Session', margin, yPos);
  yPos += 8;

  const safetyRules = [
    'Wear safety glasses and follow manufacturer\'s load data exactly',
    'Work in well-ventilated, organized area free from distractions',
    'Never exceed maximum published loads - start 10% below max',
    'Use only one powder type at a time and clearly label containers',
    'Inspect every case for cracks, splits, or defects',
    'Double-check powder charges - never rely on volume alone',
    'Keep detailed records of all loads (date, components, results)',
    'Store primers and powder separately in approved containers',
    'Never smoke or use open flames near reloading components',
    'Test fire new loads at reduced velocity before full-power loads'
  ];

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  safetyRules.forEach((rule) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    // Checkbox
    doc.rect(margin, yPos - 3, 4, 4);
    // Rule text
    const lines = doc.splitTextToSize(rule, pageWidth - margin * 2 - 10);
    doc.text(lines, margin + 8, yPos);
    yPos += (lines.length * 5) + 3;
  });

  // Pre-Session Setup Checklist
  yPos += 10;
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Pre-Session Setup Checklist', margin, yPos);
  yPos += 8;

  const setupChecks = [
    'Clean, organized workspace with adequate lighting',
    'All tools and equipment within easy reach',
    'Reloading manual(s) readily available',
    'Scale calibrated and verified with check weight',
    'Dies properly installed and adjusted for caliber',
    'Only ONE powder container on bench (clearly labeled)',
    'Primer tray organized and accessible',
    'Case gauge and calipers within reach',
    'Logbook and pen ready for documentation',
    'First aid kit nearby',
    'Phone available for emergencies',
    'No distractions (TV off, minimal interruptions)'
  ];

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  setupChecks.forEach((check) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    const lines = doc.splitTextToSize(check, pageWidth - margin * 2 - 10);
    doc.text(lines, margin + 8, yPos);
    yPos += (lines.length * 5) + 3;
  });

  // Post-Session Checklist
  yPos += 10;
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Post-Session Checklist', margin, yPos);
  yPos += 8;

  const postChecks = [
    'All ammunition properly labeled with load data',
    'Powder container sealed and stored properly',
    'Primers returned to storage container',
    'All cases cleaned and stored appropriately',
    'Dies cleaned and stored',
    'Scale returned to protective case',
    'Work area cleaned and organized',
    'All load data recorded in logbook',
    'Loaded ammunition stored safely away from heat/sparks'
  ];

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  postChecks.forEach((check) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    const lines = doc.splitTextToSize(check, pageWidth - margin * 2 - 10);
    doc.text(lines, margin + 8, yPos);
    yPos += (lines.length * 5) + 3;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const footer = 'Generated by Arms Complex - For educational purposes only. Always consult multiple load manuals.';
  doc.text(footer, pageWidth / 2, 285, { align: 'center' });

  doc.save('Reloading-Safety-Checklist.pdf');
};

export const generateProcessChecklistPDF = () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Step-by-Step Reloading Process', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Complete this checklist for each batch of ammunition', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 15;
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Batch Information
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Batch Information', margin, yPos);
  yPos += 8;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const infoFields = [
    'Date: _______________',
    'Caliber: _______________',
    'Bullet: _______________ Weight: _____ gr',
    'Powder: _______________ Lot #: _______________',
    'Charge Weight: _____ gr',
    'Primer: _______________',
    'Brass: _______________ Firings: _____',
    'OAL: _____ inches',
    'Quantity: _____ rounds'
  ];

  infoFields.forEach((field) => {
    doc.text(field, margin, yPos);
    yPos += 6;
  });

  yPos += 10;
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Step-by-step process
  const steps = [
    {
      title: 'Step 1: Case Inspection & Sorting',
      items: [
        'Visually inspect all cases for cracks or splits',
        'Check case mouths for damage',
        'Inspect case heads for cracks or separation',
        'Sort by headstamp/manufacturer',
        'Discard damaged cases',
        'Count cases: _____ accepted, _____ rejected'
      ]
    },
    {
      title: 'Step 2: Case Cleaning',
      items: [
        'Load cases into tumbler/ultrasonic cleaner',
        'Clean for appropriate time (2-4 hours)',
        'Separate cases from media thoroughly',
        'Inspect for remaining debris',
        'Dry cases completely if wet cleaned'
      ]
    },
    {
      title: 'Step 3: Depriming & Sizing',
      items: [
        'Lubricate cases with sizing lube',
        'Verify sizing die is properly adjusted',
        'Run each case through sizing die',
        'Inspect sized cases for proper dimensions',
        'Remove all sizing lube from cases'
      ]
    },
    {
      title: 'Step 4: Case Trimming & Preparation',
      items: [
        'Measure case length with calipers',
        'Trim cases exceeding max length',
        'Chamfer inside of case mouth',
        'Deburr outside of case mouth',
        'Verify all cases within spec: _____'
      ]
    },
    {
      title: 'Step 5: Priming',
      items: [
        'Clean primer pockets if needed',
        'Select proper primer type',
        'Verify primer orientation (anvil up)',
        'Seat primers to proper depth',
        'Inspect for uniform seating',
        'Count primed cases: _____'
      ]
    },
    {
      title: 'Step 6: Powder Charging (CRITICAL)',
      items: [
        'Verify only ONE powder on bench',
        'Calibrate scale with check weight',
        'Set target charge weight: _____ gr',
        'Weigh each charge individually',
        'Visual inspection of EVERY case',
        'Record min/max charges: _____ / _____ gr'
      ]
    },
    {
      title: 'Step 7: Bullet Seating',
      items: [
        'Adjust seating die to target OAL',
        'Seat test bullet and verify OAL',
        'Seat bullets in all cases',
        'Check OAL every 10 rounds',
        'Verify OAL range: _____ to _____ inches'
      ]
    },
    {
      title: 'Step 8: Crimping (If Applicable)',
      items: [
        'Adjust crimp die per instructions',
        'Crimp test round and verify',
        'Apply crimp to all rounds',
        'Inspect crimp uniformity'
      ]
    },
    {
      title: 'Step 9: Final Inspection',
      items: [
        'Measure sample of completed rounds',
        'Check all rounds chamber smoothly',
        'Use case gauge to verify dimensions',
        'Visual inspection for defects',
        'Label ammunition with load data',
        'Record in logbook'
      ]
    }
  ];

  steps.forEach((step, index) => {
    if (yPos > 250 || (index > 0 && yPos > 200)) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(step.title, margin, yPos);
    yPos += 7;

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    
    step.items.forEach((item) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.rect(margin + 5, yPos - 3, 3, 3);
      const lines = doc.splitTextToSize(item, pageWidth - margin * 2 - 12);
      doc.text(lines, margin + 10, yPos);
      yPos += (lines.length * 4) + 2;
    });

    yPos += 5;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const footer = 'Generated by Arms Complex - Always follow published load data and safety protocols';
  doc.text(footer, pageWidth / 2, 285, { align: 'center' });

  doc.save('Reloading-Process-Checklist.pdf');
};

export const generateEquipmentChecklistPDF = () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Reloading Equipment Checklist', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Essential and recommended equipment for safe reloading', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 15;
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Essential Equipment
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Essential Equipment (Required)', margin, yPos);
  yPos += 8;

  const essentialEquipment = [
    { item: 'Reloading Press', note: 'Single-stage or progressive' },
    { item: 'Die Set', note: 'Caliber-specific sizing and seating dies' },
    { item: 'Shell Holder', note: 'Matches your cartridge rim diameter' },
    { item: 'Powder Scale', note: 'Digital or balance beam (0.1 grain accuracy)' },
    { item: 'Powder Measure', note: 'For consistent charge dispensing' },
    { item: 'Powder Funnel', note: 'Caliber-specific' },
    { item: 'Case Trimmer', note: 'Manual or powered' },
    { item: 'Chamfer/Deburr Tool', note: 'Inside and outside' },
    { item: 'Calipers', note: 'Digital recommended (0.001" accuracy)' },
    { item: 'Priming Tool', note: 'Hand primer or press-mounted' },
    { item: 'Case Lube', note: 'For sizing operations' },
    { item: 'Loading Block', note: 'Hold cases during process' },
    { item: 'Reloading Manuals', note: 'Multiple sources recommended' },
    { item: 'Safety Glasses', note: 'ANSI-rated' }
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  essentialEquipment.forEach((equip) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    doc.text(equip.item, margin + 8, yPos);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    doc.text(`(${equip.note})`, margin + 55, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    yPos += 6;
  });

  // Highly Recommended Equipment
  yPos += 10;
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Highly Recommended Equipment', margin, yPos);
  yPos += 8;

  const recommendedEquipment = [
    { item: 'Case Tumbler/Ultrasonic', note: 'For cleaning brass' },
    { item: 'Case Gauge', note: 'Verify proper dimensions' },
    { item: 'Bullet Puller', note: 'Kinetic or collet type' },
    { item: 'Powder Trickler', note: 'Fine charge adjustment' },
    { item: 'Dial Indicator', note: 'For precise die adjustment' },
    { item: 'Case Neck Brush', note: 'Clean inside case necks' },
    { item: 'Primer Pocket Tool', note: 'Clean primer pockets' },
    { item: 'Media Separator', note: 'If using tumbler' },
    { item: 'Headspace Gauge', note: 'Check case dimensions' },
    { item: 'Logbook/Notebook', note: 'Document all loads' }
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  recommendedEquipment.forEach((equip) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    doc.text(equip.item, margin + 8, yPos);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    doc.text(`(${equip.note})`, margin + 55, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    yPos += 6;
  });

  // Advanced/Precision Equipment
  yPos += 10;
  if (yPos > 240) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Advanced/Precision Equipment (Optional)', margin, yPos);
  yPos += 8;

  const advancedEquipment = [
    { item: 'Concentricity Gauge', note: 'Check bullet runout' },
    { item: 'Annealing Machine', note: 'Brass case annealing' },
    { item: 'Chronograph', note: 'Measure velocity' },
    { item: 'Powder Dispenser', note: 'Automatic electronic' },
    { item: 'Case Comparator', note: 'Measure to ogive' },
    { item: 'Flash Hole Deburr', note: 'Uniform flash holes' },
    { item: 'Neck Turner', note: 'Uniform case neck thickness' },
    { item: 'Arbor Press', note: 'Precision seating' }
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  advancedEquipment.forEach((equip) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    doc.text(equip.item, margin + 8, yPos);
    doc.setFont('helvetica', 'italic');
    doc.setTextColor(100);
    doc.text(`(${equip.note})`, margin + 55, yPos);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    yPos += 6;
  });

  // Components Checklist
  if (yPos > 220) {
    doc.addPage();
    yPos = 20;
  } else {
    yPos += 10;
  }
  
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Reloading Components', margin, yPos);
  yPos += 8;

  const components = [
    'Brass Cases (new or once-fired)',
    'Bullets (appropriate weight and type)',
    'Powder (appropriate for caliber and bullet weight)',
    'Primers (correct size: small/large, rifle/pistol)',
    'Case Lube',
    'Cleaning Media (if using tumbler)'
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  
  components.forEach((component) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.rect(margin, yPos - 3, 4, 4);
    doc.text(component, margin + 8, yPos);
    yPos += 6;
  });

  // Notes section
  yPos += 10;
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }
  
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Notes / Equipment to Purchase:', margin, yPos);
  yPos += 8;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  for (let i = 0; i < 6; i++) {
    doc.text('_____________________________________________________________', margin, yPos);
    yPos += 7;
  }

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const footer = 'Generated by Arms Complex - Build your reloading setup systematically';
  doc.text(footer, pageWidth / 2, 285, { align: 'center' });

  doc.save('Reloading-Equipment-Checklist.pdf');
};

export const generateLoadDataSheetPDF = () => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Load Development Data Sheet', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Record and track your load development results', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 15;
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // Session Information
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Session Information', margin, yPos);
  yPos += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const sessionFields = [
    'Date: _______________ Time: _______________',
    'Location/Range: _______________________________________________',
    'Temperature: ______°F   Wind: ______mph   Direction: ___________',
    'Humidity: ______%   Altitude: ____________ ft',
    ''
  ];

  sessionFields.forEach((field) => {
    doc.text(field, margin, yPos);
    yPos += 5;
  });

  yPos += 5;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Firearm Information', margin, yPos);
  yPos += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const firearmFields = [
    'Firearm: _______________________________________________',
    'Caliber: _______________ Barrel Length: ______"   Twist: 1:_____"',
    'Action Type: _______________________________________________',
    'Scope/Sights: _______________________________________________',
    'Zero Distance: _________ yds'
  ];

  firearmFields.forEach((field) => {
    doc.text(field, margin, yPos);
    yPos += 5;
  });

  yPos += 5;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Load Components', margin, yPos);
  yPos += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const loadFields = [
    'Brass: _______________ Lot#: _______ Firings: _____ Trim: _____"',
    'Bullet: _______________ Weight: _____ gr   Type: _______________',
    'Powder: _______________ Lot#: _______________ Type: ___________',
    'Primer: _______________ Type: _______________',
    'Overall Length (OAL): ________"   Coal vs Lands: _______"',
    'Crimp: Yes / No   Amount: _______________'
  ];

  loadFields.forEach((field) => {
    doc.text(field, margin, yPos);
    yPos += 5;
  });

  // Test Results Table
  yPos += 10;
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Test Results', margin, yPos);
  yPos += 7;

  // Table headers
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  const colWidths = [15, 20, 20, 25, 25, 25, 20];
  const headers = ['Load#', 'Charge(gr)', 'Velocity(fps)', 'Group Size(in)', 'ES(fps)', 'SD(fps)', 'Notes'];
  let xPos = margin;
  
  headers.forEach((header, i) => {
    doc.text(header, xPos, yPos);
    xPos += colWidths[i];
  });
  
  yPos += 2;
  doc.setLineWidth(0.3);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 5;

  // Table rows (10 rows)
  doc.setFont('helvetica', 'normal');
  for (let i = 1; i <= 10; i++) {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      // Repeat headers
      xPos = margin;
      doc.setFont('helvetica', 'bold');
      headers.forEach((header, j) => {
        doc.text(header, xPos, yPos);
        xPos += colWidths[j];
      });
      yPos += 2;
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 5;
      doc.setFont('helvetica', 'normal');
    }
    
    xPos = margin;
    doc.text(i.toString(), xPos, yPos);
    xPos += colWidths[0];
    
    for (let j = 1; j < headers.length; j++) {
      doc.text('________', xPos, yPos);
      xPos += colWidths[j];
    }
    
    yPos += 6;
  }

  // Observations section
  yPos += 5;
  if (yPos > 240) {
    doc.addPage();
    yPos = 20;
  }

  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Observations & Notes', margin, yPos);
  yPos += 7;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const observations = [
    'Pressure Signs: _______________________________________________',
    '______________________________________________________________',
    'Accuracy Notes: _______________________________________________',
    '______________________________________________________________',
    'Best Performing Load: _________________________________________',
    'Issues/Problems: ______________________________________________',
    '______________________________________________________________',
    'Next Steps: ___________________________________________________',
    '______________________________________________________________'
  ];

  observations.forEach((line) => {
    if (yPos > 275) {
      doc.addPage();
      yPos = 20;
    }
    doc.text(line, margin, yPos);
    yPos += 5;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const footer = 'Generated by Arms Complex - Document all loads for safety and accuracy optimization';
  doc.text(footer, pageWidth / 2, 285, { align: 'center' });

  doc.save('Load-Development-Data-Sheet.pdf');
};
